templateDir: ./sdk-resources/beta-resources
packageName: sailpointbetasdk
packageVersion: 0.1.0
generateInterfaces: false
enumClassPrefix: false
disallowAdditionalPropertiesIfNotPresent: false
useOneOfDiscriminatorLookup: false