templateDir: ./sdk-resources/v3-resources
packageName: sailpointsdk
packageVersion: 0.1.0
generateInterfaces: false
enumClassPrefix: false
disallowAdditionalPropertiesIfNotPresent: false
useOneOfDiscriminatorLookup: false